### ISSUE TITLE
Fix the basilisk-related machinery

### ISSUE THREAD

**Issue by LTLA** [hubentu/Rcwl#4]
See the instructions in the vignette:

- You need a `.BBSoptions` file to indicate that 32-bit windows is not supported.
- **basilisk** should be loaded on first use, not as part of the package load.
- You need to turn off staged installs.

The first two points are causing a 32-bit version of Python to take precedence over the intended 64-bit version, resulting in failures on Riesling for **basilisk** and its clients. I have now prevented **basilisk** from using a 32-bit installer, so you'll end up with an explicit install-time failure for **Rcwl** on multi-arch builds for Windows.

**Comment by hubentu** [comment]
Updated. Thanks! @LTLA

**Comment by hubentu** [comment]
Skip the windows system at the end because the python module `cwltool` requires docker in the windows system. The Bioconductor build machine doesn't have docker installed so it will fail in the building step.
